spring.application.name=EjadWebApplication

spring.datasource.url=jdbc:mysql://localhost:3306/ejad
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

gemini.api.key=${GEMINI_API_KEY}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=eazmirara@gmail.com
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop

spring.web.error.include-message=always
spring.web.error.include-stacktrace=always

openai.api.key=${OPENAI_API_KEY}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

ai.model=gemini-3.5-flash-lite
google.maps.api.key=${GOOGLE_MAPS_API_KEY:}

spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

ultramsg.instance.id=${ULTRAMSG_INSTANCE_ID}
ultramsg.token=${ULTRAMSG_TOKEN}
